name: Cloud Foundry CLI GitHub Action
on:
    push:
        branches:
            [main]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: elliottpope/cloudfoundry-cli-action@v7
          with:
            CF_API: https://api.cf.us10-001.hana.ondemand.com/ #Cloud Foundry APIエンドポイント
            USERNAME: ${{ secrets.CF_USER }} #github上のsecretで設定
            PASSWORD: ${{ secrets.CF_PASSWORD }} #github上のsecretで設定
            ORG: e11a697dtrial_trial-dq7e7sz0_ext #Cloud Foundry組織名
            SPACE: trialA #Cloud Foundry領域名
            COMMAND: push employeeList-app #APIを各自修正
