name: Deploy to SAP Cloud Foundry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Install Cloud Foundry CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -O cf-cli.deb https://github.com/cloudfoundry/cli/releases/download/v8.9.0/cf8-cli-installer_8.9.0_x86-64.deb
          sudo dpkg -i cf-cli.deb
          sudo apt-get install -f

      - name: Log in to Cloud Foundry
        run: |
          cf api https://api.cf.us10-001.hana.ondemand.com/
          cf auth "${{ secrets.CF_USER }}" "${{ secrets.CF_PASSWORD }}"
          cf target -o "${{ secrets.CF_ORG }}" -s "${{ secrets.CF_SPACE }}"

      - name: Deploy to Cloud Foundry
        run: cf push "${{ secrets.CF_APP }}"
