name: Deploy to CF

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Remove Old Cloud Foundry CLI
        run: |
          sudo apt-get remove cf-cli -y

      - name: Install Cloud Foundry CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -O cf8-cli-installer_8.9.0_x86-64.deb https://github.com/cloudfoundry/cli/releases/download/v8.9.0/cf8-cli-installer_8.9.0_x86-64.deb
          sudo dpkg -i cf8-cli-installer_8.9.0_x86-64.deb
          sudo apt-get install -f

      - name: Deploy to Cloud Foundry
        uses: elliottpope/cloudfoundry-cli-action@v6
        with:
          CF_API: https://api.cf.us10-001.hana.ondemand.com/
          USERNAME: "kazuma.tamura@akkodis.co.jp"
          PASSWORD: "Modi#2410"
          ORG: "e11a697dtrial_trial-dq7e7sz0_ext"
          SPACE: "trialA"
          COMMAND: cf push
