

name: Deploy to CF

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Deploy to Cloud Foundry
        uses: cloudfoundry/cf-cli-action@v1
        with:
          cf_api: https://api.cf.us10-001.hana.ondemand.com/
          cf_username: "kazuma.tamura@akkodis.co.jp"
          cf_password: "Modi#2410"
          cf_organization: "e11a697dtrial_trial-dq7e7sz0_ext"
          cf_space: "trialA"
          command: cf push
          
