name: Deploy to CF

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Install Cloud Foundry CLI
        run: |
          sudo apt-get update
          sudo apt-get install wget
          wget -O cf-cli.deb https://packages.cloudfoundry.org/stable?release=debian64&version=v8&source=github
          sudo dpkg -i cf-cli.deb

      - name: Deploy to Cloud Foundry
        uses: elliottpope/cloudfoundry-cli-action@v6
        with:
          CF_API: https://api.cf.us10-001.hana.ondemand.com/
          USERNAME: "kazuma.tamura@akkodis.co.jp"
          PASSWORD: "Modi#2410"
          ORG: "e11a697dtrial_trial-dq7e7sz0_ext"
          SPACE: "trialA"
          COMMAND: cf push
