name: Deploy to CF
on:
    push:
        branches:
            [main]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: SAPTest/cloudfoundry-cli-action@v6 #リポジトリ
          with:
            CF_API: https://api.cf.us10-001.hana.ondemand.com/ #Cloud Foundry APIエンドポイント
            USERNAME: ${{ secrets.CF_USER }}
            PASSWORD: ${{ secrets.CF_PASSWORD }}
            ORG: my-org
            SPACE: dev
            COMMAND: push my-app
